### ISSUE TITLE
 Call to private method Database::loadConnection() from context 'ServerPing'

### ISSUE THREAD

**Issue by Sh1raz** [carloshenrq/brACP#27]
Mudei para:

':Scheme'       => empty($_SERVER['REQUEST_SCHEME']) ? "" : $_SERVER['REQUEST_SCHEME'],

Resolveu @_@

**Comment by Sh1raz** [comment]
Não sei nem se é a forma correta, mas resolveu:

PHP Fatal error:  Call to private method Database::loadConnection() from context 'ServerPing'

Mudei para protected function loadConnection() e resolveu.

**Comment by carloshenrq** [comment]
Shiraz, qual a versão do seu php?

**Comment by carloshenrq** [comment]
Essa classe ai eu ta na listinha de refactor :v

**Comment by carloshenrq** [comment]
Qual sua versão do apache tbm tio?

**Comment by Sh1raz** [comment]
PHP 5.6.28 (cli) (built: Nov 10 2016 21:09:50)

Server version: Apache/2.2.15 (Unix)
Server built:   Nov 18 2016 23:48:55

**Comment by carloshenrq** [comment]
O Problema do REQUEST_SCHEME é a versão do apache.
Na instalação diz versão Apache 2.4...

**Comment by carloshenrq** [comment]
Foi alterado o titulo para o segundo problema, pois o REQUEST_SCHEME é definido na versão 2.4 do Apache (com o mod_rewrite ligado), sendo a versão que é suportada de forma oficial pelo brACP.

https://httpd.apache.org/docs/trunk/mod/mod_rewrite.html
