### ISSUE TITLE
Problema na instalação

### ISSUE THREAD

**Issue by Sh1raz** [carloshenrq/brACP#29]
Eae, após refazer o processo de instalação porém dessa vez em um servidor mais atualizado, ocorreu aquele erro de Slim blablabla, ativei o modo dev e pelo debug descobri que as tabelas do painel não foram importadas... Tive que fazer manualmente denovo, será que estou fazendo algo errado?

PHP Warning:  include(license): failed to open stream: No such file or directory in /home/ec2-user/apache/public_html/bracp/install.php on line 605

PHP Warning:  include(): Failed opening 'license' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /home/ec2-user/apache/public_html/bracp/install.php on line 605

Foram as unicas coisas que encontrei no log.

php info: http://52.67.3.0/
cp: http://52.67.3.0/bracp/home/index/

**Comment by carloshenrq** [comment]
A Parte mais estranha é a que não estão aparecendo as imagens.
Era pra estar aparecendo de boas na sua instalação.

**Comment by Sh1raz** [comment]
Hmm, deveria existir uma pasta assets? Não tô achando em lugar algum.

**Comment by carloshenrq** [comment]
Asset é um controller em /brACP/app/Controller/Asset.php

**Comment by carloshenrq** [comment]
Se você reparar, somente as imagens não estão gerando... vou dar uma olhadinha direito depois...
Você pode postar seu arquivo de configuração aqui?

**Comment by Sh1raz** [comment]
Sim, aqui: http://pastebin.com/raw/ai99f8x2

**Comment by carloshenrq** [comment]
Ok, logo mais dou uma olhada com calma ^~^
Vou postar o arquivo aqui, pra futura referência visto que o pastebin faz a limpeza de alguns dados.
	<?php
	/**
	 * Este arquivo de instalação foi gerado pelo programa de instalação do brACP
	 * Esta cópia do brACP foi instalada em 2016-12-16 15:18:03
	 * ---- Versão do brACP:   0.2.2-beta
	 * ---- URL de Instalação: http://52.67.3.0/bracp/
	 */

	DEFINE('BRACP_VERSION', '0.2.2-beta', false);
	DEFINE('BRACP_URL', 'http://52.67.3.0/bracp/', false);
	DEFINE('BRACP_DIR_INSTALL_URL', '/bracp/', false);
	DEFINE('BRACP_TEMPLATE_DIR', '/home/ec2-user/apache/public_html/bracp/templates', false);
	DEFINE('BRACP_ENTITY_DIR', '/home/ec2-user/apache/public_html/bracp/app/Model', false);
	DEFINE('BRACP_DEFAULT_TIMEZONE', 'UTC', false);
	DEFINE('BRACP_REGEXP_EMAIL', '[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}', false);
	DEFINE('BRACP_RECAPTCHA_ENABLED', false, false);
	DEFINE('BRACP_RECAPTCHA_PRIVATE_KEY', false, false);
	DEFINE('BRACP_RECAPTCHA_PUBLIC_KEY', false, false);
	DEFINE('BRACP_RECAPTCHA_PRIVATE_URL', 'https://www.google.com/recaptcha/api/siteverify', false);
	DEFINE('BRACP_ALLOW_MAIL_SEND', false, false);
	DEFINE('BRACP_MAIL_HOST', false, false);
	DEFINE('BRACP_MAIL_PORT', 25, false);
	DEFINE('BRACP_MAIL_USER', false, false);
	DEFINE('BRACP_MAIL_PASS', false, false);
	DEFINE('BRACP_MAIL_FROM', false, false);
	DEFINE('BRACP_MAIL_FROM_NAME', false, false);
	DEFINE('BRACP_ALLOW_CREATE_ACCOUNT', 1, false);
	DEFINE('BRACP_MD5_PASSWORD_HASH', false, false);
	DEFINE('BRACP_MAIL_REGISTER_ONCE', false, false);
	DEFINE('BRACP_ALLOW_CHANGE_MAIL', false, false);
	DEFINE('BRACP_CHANGE_MAIL_DELAY', 60, false);
	DEFINE('BRACP_CONFIRM_ACCOUNT', false, false);
	DEFINE('BRACP_ALLOW_RECOVER', false, false);
	DEFINE('BRACP_RECOVER_BY_CODE', false, false);
	DEFINE('BRACP_RECOVER_CODE_EXPIRE', 120, false);
	DEFINE('BRACP_RECOVER_STRING_LENGTH', 8, false);
	DEFINE('BRACP_RECOVER_RANDOM_STRING', 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', false);
	DEFINE('BRACP_NOTIFY_CHANGE_PASSWORD', false, false);
	DEFINE('BRACP_NOTIFY_CHANGE_MAIL', false, false);
	DEFINE('BRACP_ALLOW_LOGIN_GMLEVEL', 0, false);
	DEFINE('BRACP_ALLOW_ADMIN_GMLEVEL', 99, false);
	DEFINE('BRACP_ALLOW_ADMIN_CHANGE_PASSWORD', false, false);
	DEFINE('BRACP_SQL_CP_DRIVER', 'pdo_mysql', false);
	DEFINE('BRACP_SQL_CP_HOST', '127.0.0.1', false);
	DEFINE('BRACP_SQL_CP_USER', 'bracp1', false);
	DEFINE('BRACP_SQL_CP_PASS', '', false);
	DEFINE('BRACP_SQL_CP_DBNAME', 'brathena_cp', false);
	DEFINE('BRACP_SQL_DB_DRIVER', 'pdo_mysql', false);
	DEFINE('BRACP_SQL_DB_HOST', '127.0.0.1', false);
	DEFINE('BRACP_SQL_DB_USER', 'bracp1', false);
	DEFINE('BRACP_SQL_DB_PASS', '', false);
	DEFINE('BRACP_SQL_DB_DBNAME', 'brathena_db', false);
	DEFINE('BRACP_CACHE', 1, false);
	DEFINE('BRACP_CACHE_EXPIRE', 600, false);
	DEFINE('BRACP_SESSION_SECURE', 1, false);
	DEFINE('BRACP_SESSION_ALGO', 'AES-256-ECB', false);
	DEFINE('BRACP_SESSION_KEY', 'ZKprp9qW8D6XfXLPKqXyXFbryOCKIoyCDSdTMEjLNOU=', false);
	DEFINE('BRACP_SESSION_IV', false, false);
	DEFINE('BRACP_DEVELOP_MODE', true, false);
	DEFINE('BRACP_MAINTENCE', false, false);
	DEFINE('BRACP_ALLOW_ADMIN', false, false);
	DEFINE('BRACP_ALLOW_CHOOSE_THEME', 1, false);
	DEFINE('BRACP_ALLOW_RANKING', 1, false);
	DEFINE('BRACP_ALLOW_RANKING_ZENY', 1, false);
	DEFINE('BRACP_ALLOW_RANKING_ZENY_SHOW_ZENY', 1, false);
	DEFINE('BRACP_ALLOW_SHOW_CHAR_STATUS', false, false);
	DEFINE('BRACP_DEFAULT_THEME', 'classic', false);
	DEFINE('BRACP_DEFAULT_LANGUAGE', 'pt_BR', false);
	DEFINE('BRACP_SRV_PING_DELAY', 300, false);
	DEFINE('BRACP_ALLOW_VENDING', false, false);
	DEFINE('BRACP_ALLOW_MODS', false, false);
	DEFINE('BRACP_MODS_DIR', '/home/ec2-user/apache/public_html/bracp/mods', false);
	DEFINE('BRACP_ALLOW_EXTERNAL_REQUEST', false, false);
	DEFINE('BRACP_PASS_CHANGE_ALERT', 30, false);
	DEFINE('BRACP_LOG_IP_DETAILS', false, false);
	DEFINE('BRACP_SRV_0_NAME', 'brAthena', false);
	DEFINE('BRACP_SRV_0_LOGIN_IP', '127.0.0.1', false);
	DEFINE('BRACP_SRV_0_LOGIN_PORT', '6900', false);
	DEFINE('BRACP_SRV_0_CHAR_IP', '127.0.0.1', false);
	DEFINE('BRACP_SRV_0_CHAR_PORT', '6121', false);
	DEFINE('BRACP_SRV_0_MAP_IP', '127.0.0.1', false);
	DEFINE('BRACP_SRV_0_MAP_PORT', '5121', false);
	DEFINE('BRACP_SRV_0_SQL_DRIVER', 'pdo_mysql', false);
	DEFINE('BRACP_SRV_0_SQL_HOST', '127.0.0.1', false);
	DEFINE('BRACP_SRV_0_SQL_USER', 'bracp1', false);
	DEFINE('BRACP_SRV_0_SQL_PASS', '', false);
	DEFINE('BRACP_SRV_0_SQL_DBNAME', 'brathena_main', false);
	DEFINE('BRACP_REGEXP_FORMAT', 258, false);
	DEFINE('BRACP_REGEXP_USERNAME', '.{4,32}', false);
	DEFINE('BRACP_REGEXP_PASSWORD', '[a-zA-Z0-9\\s@\\$#%&\\*!]{4,32}', false);

	DEFINE('BRACP_SRV_DEFAULT', 0, false);
	DEFINE('BRACP_SRV_COUNT', 1, false);

	// Fim da instalação do brACP.

**Comment by carloshenrq** [comment]
@Sh1raz você pode fazer um update na sua instalação e tentar novamente? Acredito ter corrigido no commit https://github.com/carloshenrq/brACP/commit/9c5916fd71c6b6d00bc0d09ea9fb3a781a161393.

**Comment by Sh1raz** [comment]
Desculpa a demora.

Refiz a instalação e dessa vez foi de primeira, inclusive funcionou perfeitamente com memcache.

Há braçooo

**Comment by carloshenrq** [comment]
No test, no fear.

Não testei com o memcache ainda AUHEUHAEUHAUEHUAUEHHUAEUHAUEHHAEUHAE
Obrigado por testar.
